In [1]:
%matplotlib inline


PyTorch是什么?
================

基于Python的科学计算包，服务于以下两种场景:

-  作为NumPy的替代品，可以使用GPU的强大计算能力
-  提供最大的灵活性和高速的深度学习研究平台
    

开始
---------------

Tensors（张量）

Tensors与Numpy中的 ndarrays类似，但是在PyTorch中
Tensors 可以使用GPU进行计算.



In [2]:
from __future__ import print_function
import torch

创建一个 5x3 矩阵, 但是未初始化:



In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[-4.4156e+08,  4.5827e-41, -4.4156e+08],
        [ 4.5827e-41,  4.4842e-44,  0.0000e+00],
        [ 1.5695e-43,  0.0000e+00,  8.6170e-37],
        [ 3.0749e-41,  8.9683e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


创建一个随机初始化的矩阵:



In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2709, 0.6939, 0.5438],
        [0.7125, 0.7232, 0.0957],
        [0.6597, 0.4958, 0.7727],
        [0.5867, 0.3849, 0.7347],
        [0.4162, 0.2011, 0.1255]])


创建一个0填充的矩阵，数据类型为long:



In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


创建tensor并使用现有数据初始化:



In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖

In [12]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      #  对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.8259, -1.1479,  0.7647],
        [-1.5201,  0.0768, -0.8352],
        [ 0.3411, -0.2555,  0.0068],
        [ 0.6310, -1.3829,  1.2280],
        [-0.4805,  0.0945,  0.0920]])


获取 size

***译者注：使用size方法与Numpy的shape属性返回的相同，张量也支持shape属性，后面会详细介绍***


In [14]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 返回值是 tuple类型, 所以它支持tuple类型的所有操作.</p></div>

操作

操作有多种语法。 

我们将看一下加法运算。

加法1:

In [15]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.5265, -0.4877,  1.7440],
        [-0.6773,  0.4110, -0.5914],
        [ 0.7414,  0.3782,  0.0785],
        [ 1.3708, -0.8877,  1.8518],
        [-0.0241,  0.1490,  0.3914]])


加法2


In [16]:
print(torch.add(x, y))

tensor([[-1.5265, -0.4877,  1.7440],
        [-0.6773,  0.4110, -0.5914],
        [ 0.7414,  0.3782,  0.0785],
        [ 1.3708, -0.8877,  1.8518],
        [-0.0241,  0.1490,  0.3914]])


提供输出tensor作为参数



In [17]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.5265, -0.4877,  1.7440],
        [-0.6773,  0.4110, -0.5914],
        [ 0.7414,  0.3782,  0.0785],
        [ 1.3708, -0.8877,  1.8518],
        [-0.0241,  0.1490,  0.3914]])


替换



In [18]:
# adds x to y
y.add_(x)
print(y)

tensor([[-1.5265, -0.4877,  1.7440],
        [-0.6773,  0.4110, -0.5914],
        [ 0.7414,  0.3782,  0.0785],
        [ 1.3708, -0.8877,  1.8518],
        [-0.0241,  0.1490,  0.3914]])


<div class="alert alert-info"><h4>Note</h4><p>任何 以``_`` 结尾的操作都会用结果替换原变量.
    例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.</p></div>

你可以使用与NumPy索引方式相同的操作来进行对张量的操作



In [19]:
print(x)
print(x[:, 1])

tensor([[-1.8259, -1.1479,  0.7647],
        [-1.5201,  0.0768, -0.8352],
        [ 0.3411, -0.2555,  0.0068],
        [ 0.6310, -1.3829,  1.2280],
        [-0.4805,  0.0945,  0.0920]])
tensor([-1.1479,  0.0768, -0.2555, -1.3829,  0.0945])


``torch.view``: 可以改变张量的维度和大小

***译者注：torch.view 与Numpy的reshape类似***



In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有只有一个元素的张量，使用``.item()``来得到Python数据类型的数值


In [21]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6888])
-0.6887745261192322


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `herf <https://pytorch.org/docs/torch>`_.

NumPy 转换
------------

将一个Torch Tensor转换为NumPy数组是一件轻松的事，反之亦然。

Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。

将一个Torch Tensor转换为NumPy数组



In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


观察numpy数组的值是如何改变的。



In [24]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


 NumPy Array 转化成 Torch Tensor

使用from_numpy自动转化



In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到
NumPy 的转换.
CUDA 张量
------------

使用``.to`` 方法 可以将Tensor移动到任何设备中



In [27]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改
else:
    print('cpu')

cpu
